### Problem Set 2
#### Question 1



Problem 1

In [1]:
L=[2,7,9,3,1]
def stats(L):
    return min(L), max(L), sum(L)/len(L)
print(stats(L))

(1, 9, 4.4)


Problem 2

In [4]:
# int (immutable)
a= 5
b= a
b += 1
print(a,b)

# str (immutable)
s1 = "hello"
s2 = s1
s2 += " world"
print(s1, s2)

# list (mutable)
L1 = [1, 2, 3]
L2 = L1
L2.append(4)
print(L1, L2)

# tuple (immutable)
t1 = (1, 2, 3)
t2 = t1
t2 += (4,)
print(t1, t2)  

# set (mutable)
s1 = {1, 2, 3}
s2 = s1
s2.add(4)
print(s1, s2) 

print("""
Conclusion:
Immutable types → int, str, tuple
Mutable types   → list, set
""")


5 6
hello hello world
[1, 2, 3, 4] [1, 2, 3, 4]
(1, 2, 3) (1, 2, 3, 4)
{1, 2, 3, 4} {1, 2, 3, 4}

Conclusion:
Immutable types → int, str, tuple
Mutable types   → list, set



Problem 3
Solution is provided in `calculator.py` and `solution.py`.


#### Question 2

Problem 1


In [8]:
import numpy as np
def matrix_product():
    A = np.array([[3,-1,4], [1,5,-9]])
    B = np.array([[2,6,-5,3], [5,-8,9,7], [9,-3,-2,-3]])
    return A @ B
print(matrix_product())

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


Problem 2

In [10]:
import numpy as np

def cayley_hamilton():
    # Define A properly
    A = np.array([[3, 1, 4],
                  [1, 5, 9],
                  [-5, 3, 1]])
    
    # Matrix powers
    A2 = A @ A        # A squared
    A3 = A @ A @ A    # A cubed
    
    # Compute expression
    result = -A3 + 9*A2 - 15*A
    return result

# Run and display result
print(cayley_hamilton())



[[0 0 0]
 [0 0 0]
 [0 0 0]]


Problem 5

In [11]:
import numpy as np

def block_matrix():
    # Define matrices
    A = np.array([[0, 2, 4],
                  [1, 3, 5]])
    
    B = np.array([[3, 0, 0],
                  [3, 3, 0],
                  [3, 3, 3]])
    
    C = np.array([[-2, 0, 0],
                  [ 0, -2, 0],
                  [ 0,  0, -2]])
    
    # Identity matrix
    I = np.eye(3, dtype=int)
    
    # Zero blocks
    Z22 = np.zeros((2,2), dtype=int)  # 2x2
    Z23 = np.zeros((2,3), dtype=int)  # 2x3
    Z32 = np.zeros((3,2), dtype=int)  # 3x2
    Z33 = np.zeros((3,3), dtype=int)  # 3x3
    
    # Assemble block matrix using stacking
    top    = np.hstack((Z33, A.T, I))
    middle = np.hstack((A, Z22, Z23))
    bottom = np.hstack((B, Z32, C))
    
    
    result = np.vstack((top, middle, bottom))
    return result

print(block_matrix())


[[ 0  0  0  0  1  1  0  0]
 [ 0  0  0  2  3  0  1  0]
 [ 0  0  0  4  5  0  0  1]
 [ 0  2  4  0  0  0  0  0]
 [ 1  3  5  0  0  0  0  0]
 [ 3  0  0  0  0 -2  0  0]
 [ 3  3  0  0  0  0 -2  0]
 [ 3  3  3  0  0  0  0 -2]]


#### Question 3

Problem 1

In [1]:

class Backpack:
    """
    A Backpack object class. Has a name, color, max_size, and a list of contents.
    
    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): maximum number of items allowed in the backpack.
        contents (list): the contents of the backpack.
    """

    def __init__(self, name, color, max_size=5):
        """
        Initialize a Backpack object with owner name, color, and maximum size.
        
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int, optional): the maximum number of items the backpack can hold.
                                      Defaults to 5.
        """
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
      

    def put(self, item):
        """
        Add 'item' to the backpack if there is room.
        If the backpack already has max_size items, print "No Room!" instead.
        
        Parameters:
            item (str): the item to add to the backpack.
        """
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def take(self, item):
        """
        Remove 'item' from the backpack's list of contents.
        
        Parameters:
            item (str): the item to remove from the backpack.
        """
        self.contents.remove(item)
    def dump(self):
        """
        Empty the backpack's contents completely.
        """
        self.contents = []


# Test function
def test_backpack():
    testpack = Backpack("Barry", "black")  # Instantiate the object.
    
    # Test attribute assignment
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    if testpack.color != "black":
        print("Backpack.color assigned incorrectly")
    if testpack.max_size != 5:
        print("Backpack.max_size assigned incorrectly")

    # Test methods
    for item in ["pencil", "pen", "paper", "computer", "eraser", "book"]:
        testpack.put(item)

    print("Contents after adding items:", testpack.contents)

    # Test dump method
    testpack.dump()
    print("Contents after dump:", testpack.contents)
    print("Contents after dump:", testpack.contents)
    if testpack.contents != []:
        print("Dump method failed!")


# Run test
test_backpack()


No Room!
Contents after adding items: ['pencil', 'pen', 'paper', 'computer', 'eraser']
Contents after dump: []
Contents after dump: []


Problem 2

In [3]:
class Jetpack(Backpack):
    """
    A Jetpack object class. Inherits from Backpack.
    A jetpack is a special kind of backpack that also stores fuel.

    Attributes:
        name (str): the name of the jetpack's owner.
        color (str): the color of the jetpack.
        max_size (int): maximum number of items the jetpack can hold (default = 2).
        contents (list): the contents of the jetpack.
        fuel (int): the amount of fuel available (default = 10).
    """

    def __init__(self, name, color, max_size=2, fuel=10):
        """
        Parameters:
            name (str): the name of the jetpack's owner.
            color (str): the color of the jetpack.
            max_size (int, optional): the maximum number of items allowed (default=2).
            fuel (int, optional): the initial amount of fuel (default=10).
        """
        # Call Backpack constructor for name, color, max_size
        super().__init__(name, color, max_size)
        self.fuel = fuel

    def fly(self, fuel_burn):
        """
        Burn the given amount of fuel from the jetpack.

        Parameters:
            fuel_burn (int): the amount of fuel to burn.

        Behavior:
            - If not enough fuel remains, print "Not enough fuel!"
            - Otherwise, subtract fuel_burn from self.fuel.
        """
        if fuel_burn > self.fuel:
            print("Not enough fuel!")
        else:
            self.fuel -= fuel_burn

    def dump(self):
        """
        Empty the jetpack completely:
        - Removes all contents
        - Empties the fuel tank
        """
        super().dump()   # clear contents
        self.fuel = 0


# ✅ test function should NOT be indented under dump()
def test_jetpack():
    jet = Jetpack("Hinata", "Purple")  # defaults: max_size=2, fuel=10
    
    # Test attributes
    print("Owner:", jet.name)
    print("Color:", jet.color)
    print("Max size:", jet.max_size)
    print("Initial fuel:", jet.fuel)
    print("Contents:", jet.contents)

    # Test put (capacity check inherited from Backpack)
    jet.put("wrench")
    jet.put("medkit")
    jet.put("extra battery")  # should trigger "No Room!"
    print("Contents after adding:", jet.contents)

    # Test fly
    jet.fly(5)   # should succeed
    jet.fly(10)  # should print "Not enough fuel!"

    # Test dump
    jet.dump()
    print("Contents after dump:", jet.contents)
    print("Fuel after dump:", jet.fuel)


# Run the test
test_jetpack()


Owner: Hinata
Color: Purple
Max size: 2
Initial fuel: 10
Contents: []
No Room!
Contents after adding: ['wrench', 'medkit']
Not enough fuel!
Contents after dump: []
Fuel after dump: 0
